version: "3.8"

x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - PYTHONPATH=/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts

x-airflow-image: &airflow_image apache/airflow:2.7.3-python3.8

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    networks:
      - airflow_net

  init:
    image: manning-airflow/airflow
    depends_on:
      - postgres
    env_file:
      - .env
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    networks:
      - airflow_net

  webserver:
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
      - mlflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - logs:/opt/airflow/logs
    env_file:
      - .env
    environment: *airflow_environment
    command: webserver
    networks:
      - airflow_net

  scheduler:
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
      - mlflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - data:/opt/airflow/data
      - logs:/opt/airflow/logs
    env_file:
      - .env
    environment: *airflow_environment
    command: scheduler
    networks:
      - airflow_net

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        pip install boto3 --quiet
        mlflow server --host 0.0.0.0 \
            --default-artifact-root s3://mri-dataset/mlflow --serve-artifacts
    ports:
      - "5050:5000"
    networks:
      - airflow_net

volumes:
  data:
  logs:
  mlflow_data:

networks:
  airflow_net:
    driver: bridge
