version: "3.8" # версия формата Docker-compose
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment # создание шаблона списка переменных окружения
  # Airflow settings.
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True # хранить исходный код DAG в БД
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True # хранить сериализованные DAG-и в БД
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True # разрешает смотреть конфигурацию Airflow в Web UI
x-airflow-image: &airflow_image apache/airflow:2.7.3-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services: # описание контейнеров
  postgres:
    image: postgres:12-alpine # образ
    environment: # переменные окружения
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  init: # сервис однократной инициализации Airflow
    build: # сборка собственного образа
      context: ./docker/airflow # папка, где лежит Dockerfile
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image # передаёт базовый образ Airflow в Dockerfile
    image: manning-airflow/airflow # имя итогового Docker-образа
    depends_on: # старт только после postgres
      - postgres
    env_file:
      - .env
    environment: *airflow_environment # использует все переменные окружения airflow
    entrypoint: /bin/bash # переопределяет стандартную точку входа
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
  webserver: # контейниер с UI Airflow
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes: # монтирует даги с хоста на контейнер
      - ./airflow/dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    environment: *airflow_environment
    command: webserver
  scheduler: # контейнер для планировщика
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - data:/opt/airflow/data
      - logs:/opt/airflow/logs # общие логи с webserver
    env_file:
      - .env
    environment: *airflow_environment
    command: scheduler

volumes:
  data:
  logs: