version: "3.8" # версия формата Docker-compose
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment # создание шаблона списка переменных окружения
  # Airflow settings.
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow

  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
x-airflow-image: &airflow_image apache/airflow:2.7.3-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services: # описание контейнеров
  postgres:
    image: postgres:12-alpine # образ
    environment: # переменные окружения
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  init:
    image: manning-airflow/airflow
    depends_on:
      - postgres
    env_file:
      - .env
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
  webserver: # контейниер с UI Airflow
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes: # монтирует даги с хоста на контейнер
      - ./airflow/dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    environment: *airflow_environment
    command: webserver
  scheduler: # контейнер для планировщика
    build:
      context: ./docker/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - data:/opt/airflow/data
      - logs:/opt/airflow/logs # общие логи с webserver
    env_file:
      - .env
    environment: *airflow_environment
    command: scheduler

volumes:
  data:
  logs: